ParAlg/gbbs

- .bazelrc
Adds bazel configuration option to build with (AddressSanitizer)[https://github.com/google/sanitizers/wiki/AddressSanitizer]. 
I've found this useful for debugging issues when developing locally on macOS, which doesn't have `valgrind`. Once we add tests to CI, it maybe also be useful to run tests both under the normal configuration and under this AddressSanitizer configuration.
> bazelrc: Add AddressSanitizer config

- WORKSPACE
This PR fixes warnings like
```
DEBUG: Rule 'simdinter' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1562290323 -0400"
```
--- these are indicating that we can add the `shallow_since` argument to `WORKSPACE` rules so that Bazel can perform a shallow clone of the external repositories listed. 
I also changed Googletest to be downloaded directly as a tarball instead of as a git repo, as [that's what's recommended](https://docs.bazel.build/versions/master/external.html#repository-rules) (probably because it allows specifying mirror links and because it's faster the download). 
Along the way, I updated to the latest Googletest version, from 1.8.1 to 1.10.0. No resulting regressions.
> WORKSPACE: Fix debug warnings, update GoogleTest

- ligra/bridge.h
- pbbslib/BUILD
- pbbslib/assert.h
- pbbslib/utilities.cc
- pbbslib/utilities.h
This PR adds some macros that are useful for validating internal programming logic when debugging.
I put these macros in `pbbslib/`, though I'm not so sure that's the appropriate place to put them since they're not a part of the `PBBS` codebase...
Macros:
- `ASSERT()`: the benefit of this over the C `assert()` is that an optional message can be provided, e.g., 
```cpp
int x = 0;
ABORT(x > 0, "x must be positive, was " << x << " instead");
```
on lines 44-45 of `foo/bar.cc` will print
```
foo/bar.cc:45: Failed assertion `x > 0`: x must be positive, was 0 instead
```
- `ABORT()`: takes a message as argument; the benefit of this is that `ABORT("unexpected value of x")` is more concise than always typing `std::cerr << "unexpected value of x\n"; abort()` every time we want to quit the program. …
> pbbslib: Add assertion macros

- .bazelrc
- README.md
- pbbslib/parallel.cc
- pbbslib/parallel.h
In PR #6, I broke all the makefiles by moving function definitions out of header files into new implementation files. I didn't realize this.
Now that all the makefiles are broken, we need a way to compile with Cilk with Bazel, as @yushangdi pointed out. This PR adds a way to compile with Cilk, OpenMP, or serially through Bazel.
> bazelrc: Add config options for compiling serially or with Cilk or OpenMP

- ligra/graph.h
- ligra/unit_tests/graph_test.cc
I encountered a bug in `sym_graph_from_edges`. This PR adds a fix and adds unit test that failed prior to the fix.
Consider the following graph:
```
0 -- 1    2    3
```
We construct this graph by giving the directed edges `(0, 1), (1,0)` and the number of vertices `4` to `sym_graph_from_edges`.
Now `sym_graph_from_edges` sorts the edges by the first endpoint and computes an array `starts` such that, in rough terms, `starts[i]` represents the point where vertex `i` appears as a first endpoint in the edge list. We expect `starts` to be a non-decreasing sequence since the edges are sorted.
Then by computing the differences between consecutive `starts` entries, we get the degrees of each vertex.
However, in the case where some vertices don't have any edges, the last few entries of …
> graph: bugfix for degree calculation in sym_graph_from_edges

- ligra/BUILD
- ligra/edge_map_blocked.cc
- ligra/edge_map_blocked.h
- ligra/ligra.h
The `generate*_main` macros in `ligra/ligra.h` invoke a `list_allocator` (`pbbslib/list_allocator.h`) but never call `list_allocator::finish()` to clean up at the end. This makes AddressSanitizer report a lot of memory leaks sometimes. This PR adds a clean up call at the end of these `generate*_main` macros.
(AddressSanitizer still reports memory leaks after this --- e.g, in `WorkEfficientSDB14`, it reports leaks regarding the entries in `emhelper::perthread_blocks`. That leak looks harder to debug though since there's trickier logic happening there, so I'm not going to deal with it right now.)
> ligra: Clean up list_allocator at the end of Ligra generated main

- README.md
Since CI uses g++ version 7.4.0, that's the only version we can guarantee the code compiles with --- we should update the requirements listed in the README accordingly.
In particular, it turns out the `-Wshadow=local` flag that I added to `.bazelrc` is only available starting in GCC 7.
Unfortunately, Cilk support is also deprecated in GCC 7, and is removed entirely in Cilk GCC 8. An alternative path forward would be to just remove `-Wshadow=local` (ideally we would replace it with the much older flag `-Wshadow`, but our codebase contains too many instances of shadowing right now) and force Travis to use whatever g++ version is ideal for us.
> README: Update compiler version

- benchmarks/Connectivity/BUILD
- benchmarks/Connectivity/Framework/mains/BUILD
- benchmarks/Connectivity/Framework/mains/label_propagation.cc
- benchmarks/Connectivity/Framework/mains/liutarjan_bfs.cc
- benchmarks/Connectivity/Framework/mains/liutarjan_kout.cc
- benchmarks/Connectivity/Framework/mains/liutarjan_ldd.cc
- benchmarks/Connectivity/Framework/mains/liutarjan_nosample.cc
- benchmarks/Connectivity/Framework/mains/shiloach_vishkin.cc
- benchmarks/Connectivity/Framework/mains/uf_utils.h
- benchmarks/Connectivity/Incremental/mains/BUILD
- benchmarks/Connectivity/Incremental/mains/lt_utils.h
- benchmarks/Connectivity/Incremental/mains/uf_utils.h
- benchmarks/Connectivity/common.cc
- benchmarks/Connectivity/common.h
- benchmarks/Connectivity/connectit.cc
- benchmarks/Connectivity/connectit.h
This PR creates `common.cc` and `connectit.cc`, moving some function definitions from the respective header files to those implementation files. I de-templatized some functions along the way.
Initially, this PR was going to be a quest to de-templatize a bunch of functions in `benchmarks/Connectivity/Incremental` and `benchmarks/Connectivity/Framework`. I wanted to see whether this would reduce the compilation time of the binaries in these directories. These binaries collectively take a long time to compile on CI because there are so many binaries (on a machine with more parallelism capacity it's not as much of an issue, but CI runs with two threads). A lot of these functions take enums and booleans as template arguments rather than function arguments so that they can case on them at …
> Connectivity: Create implementation files for common.h + connectit.h

- utils/compressor.C
- utils/converter.h
`using namespace std` in these `utils/` files causes namespace conflicts when compiling when Clang on a Mac.  This PR removes those `using` statements.
> utils: Fix Clang build

- .gitignore
- scripts/run_all_benchmarks.py
This PR adds a script for running all benchmarks. Run it using a command like
```sh
python3.7 run_all_benchmarks.py --unweighted_graph=~/gbbs/inputs/rMatGraph_J_5_100 --weighted_graph=~/gbbs/inputs/rMatGraph_WJ_5_100 --timeout=60
```
It needs Python >=3.7.
The script hardcodes lists of benchmarks that should be run on an unweighted graph vs. on a weighted graph. The script checks that all benchmarks are accounted for so that no benchmarks will slip through the cracks.
We could put this into CI as an integration test, although some additional logic needs to be put into CI -- right now I'm guessing that everything would fail to run due to `pbbslib/list_allocator.h`'s `default_alloc_size` being too large for the CI machine to handle.
What this script does _not_ do:
- Does not check …
> scripts: Add script for running all benchmarks

- benchmarks/CliqueCounting/Clique.h
- benchmarks/Connectivity/LiuTarjan/Connectivity.h
- benchmarks/DegeneracyOrder/BarenboimElkin08/DegeneracyOrder.h
- benchmarks/DegeneracyOrder/GoodrichPszona11/DegeneracyOrder.h
- ligra/pbbslib/sparse_additive_map.h
- ligra/pbbslib/sparse_table.h
- ligra/vertex.h
- pbbslib/seq.h
`pbbs::range` and `pbbs::sequence` have a `T& operator[](size_t) const` operator, which has the odd effect that you can write to indices in a const `range`/`sequence`. 
This PR redefines `operator[]` on `pbbs::range` and `pbbs::sequence` so that you can write to indices in a non-`const` `range`/`sequence` but you can only read indices in a `const` `range`/`sequence`.
This should be a no-op in terms of runtime behavior.
> seq: Give operator[]  const and non-const overloads

- ligra/vertex.h
`mapInNghs()` calls `mapNghs()`, which was only using out-neighbors. This PR fixes `mapNghs()` to work for in-neighbors too.
> vertex: Fix mapInNghs()

- README.md
- benchmarks/makefile.benchmarks
- makefile.variables
- utils/.gitignore
- utils/makefile
Add Makefile for `utils/`, not including `utils/generators/`.
Other changes:
- Added `--start-group` and `--end-group` around linker objects in `makefile.benchmarks` to crudely fix link-order issues that appeared
> utils: Fix makefile

- makefile.variables
* Remove redundant flags
* Add GCC-specific vs. Clang-specific flags based on OS to remove warnings about unknown flags
> makefile.variables: Compiler flag cleanup

- CODEOWNERS
- benchmarks/SCAN/Naive/BUILD
- benchmarks/SCAN/Naive/scan.h
- benchmarks/SCAN/Naive/scan_helpers.cc
- benchmarks/SCAN/Naive/scan_helpers.h
- benchmarks/SCAN/Naive/unit_tests/BUILD
- benchmarks/SCAN/Naive/unit_tests/scan_test.cc
Add `benchmarks/SCAN/Naive`, an implementation of SCAN. 
This implementation doesn't attempt to be fast but is useful for checking correctness of other SCAN implementations (namely, I used it to check the output of `benchmarks/SCAN/IndexBased`. However, when comparing outputs of different SCAN implementations, be wary of floating point rounding differences if there are pairs of vertices whose structural similarity falls very close to the SCAN epsilon value. For this kind of comparison, it's better to set epsilon to a non-round number like 0.603 rather than 0.6 to reduce the chance of encountering these issues.
> SCAN: Add second implementation for correctness checking

- pbbslib/seq.h
Add initializer list constructor for sequence. This is useful for unit tests --- now sequences can be initialized like 
```cpp
pbbs::sequence<int> s1 = {1, 2, 3, 4, 5};
```
just like `std::vector`s can. 
One annoyance with initializer list constructors is their ambiguity with brace initialization:
```cpp
// Before adding the initializer list constructor, this would call the (size_t)
// constructor and create a sequence of 100 elements.
// After adding the initializer list constructor, this calls the
// (initializer_list<size_t>) constructor and creates a sequence of a single
// element, 100.
pbbs::sequence<size_t> s{100};
```
To check that adding this constructor doesn't change the behavior of any existing brace initializations, I checked that adding ` __attribute__((deprecated))` to the …
> seq: Add initializer list constructor

- benchmarks/SCAN/IndexBased/BUILD
- benchmarks/SCAN/IndexBased/scan.cc
- benchmarks/SCAN/IndexBased/scan.h
- benchmarks/SCAN/IndexBased/unit_tests/BUILD
- benchmarks/SCAN/IndexBased/unit_tests/scan_test.cc
- benchmarks/SCAN/IndexBased/unit_tests/utils_test.cc
- benchmarks/SCAN/IndexBased/utils.cc
- benchmarks/SCAN/IndexBased/utils.h
- move some SCAN-related functions not specific to `IndexBased` implementation into a separate `utils.h` file --- if for some reason I write more SCAN implementations, then it's easy to move the `utils.h` file out to the parent `SCAN/` directory to be shared
- add a function for computing the modularity of a clustering to `utils.h`
> SCAN/IndexBased: Add modularity implementation

- .bazelrc
- benchmarks/BFS/NonDeterministicBFS/unit_tests/BUILD
- benchmarks/SCAN/IndexBased/unit_tests/BUILD
- benchmarks/SCAN/Naive/unit_tests/BUILD
- internal_tools/build_defs.bzl
- ligra/unit_tests/BUILD
- pbbslib/unit_tests/BUILD
fixes linker warnings that occur from `bazel build -c fastbuild //pybindings:gbbs_lib.so` on macOS:
```
ld: warning: direct access in function 'unsigned long std::__1::__str_rfind<char, unsigned long, std::__1::char_traits<char>, 18446744073709551615ul>(char const*, unsigned long, char const*, unsigned long, unsigned long)' from file 'bazel-out/darwin-fastbuild/bin/pybindings/_objs/gbbs_lib.so/gbbs_lib.o' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file 'bazel-out/darwin-fastbuild/bin/ligra/libgraph_io.a(graph_io_57e27e1f35413a2143192c0c15671883.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings
```
The linker error appears because pybind bindings …
> bazelrc: Fix visibility warnings when compiling Python bindings on macOS

- WORKSPACE
- external/BUILD_simdinter.bazel
- Remove unused `graphsetinter`
- Move BUILD file contents for `simdinter` from WORKSPACE to its own file
> WORKSPACE: Clean up external repos

- gbbs/graph.h
- in `nghReduce()`, use the correct return type
- in lambda functions, explicitly capture variables declared via structured binding (implicit capture doesn't work due to Apple Clang following a buggy, now outdated part of the C++ standard https://stackoverflow.com/q/46114214/4865149 )
> graph: Fix some compilation errors for macOS Clang

- gbbs/graph_io.cc
Issue #68: In `read_unweighted_asymmetric_graph()`, `v_in_data[n - 1].degree` accessed the invalid array entry `tOffsets[n]`. (`v_in_data[i].degree` is the in-degree of each vertex i, and `tOffsets[i]` is the sum of the number of in-edges for vertices 0 to i-1 (inclusive).)
Fix: Make `tOffsets` have length `n + 1` rather than `n`. The logic that fills in `tOffsets` correctly populates `tOffsets[n] = m`.
Printed out `tOffsets` while reading in the following graphs and checked that the printed results were correct:
- 8 vertex graph with edges (2, 5), (2, 6), (3, 5), (3, 7)
- 10 vertex graph with the same edges above (to test that `tOffsets[n]` is correct when last few vertices have zero in-degree)
> graph_io: Fix out-of-bounds error for in-degree in unweighted asymmetric graphs

- gbbs/graph.h
Fixes issue described in https://github.com/ParAlg/gbbs/issues/80 by calling `deletion_fn()` at the very beginning.
Note that I only tested this fix in the context of my own algorithm implementation. I did not test this for any other benchmark/algorithm provided by gbbs.
> Fix ParAlg/gbbs#80
